POST http://localhost:3001/users/register
Content-Type: application/json

{
    "name": "test",
    "surname": "test",
    "email": "3testtest@test.com",
    "password": "testpass",
    "nickname": "2testtest"
}

###

POST http://localhost:3001/users/login 
Content-Type: application/json

{
    "email": "mukeshkuppa@test.com",
    "password": "mukeshkuppa"
}

###

POST http://localhost:3001/blogs/new
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im5pY2tzdHJ1c3NAdGVzdC5jb20iLCJ1c2VySWQiOiI2MDc5ZmYzZDQwNDJhOTE2NmMzZjNlMTciLCJpYXQiOjE2MTg2MDgwNDIsImV4cCI6MTYxODYxMTY0Mn0.4kI_ONgwyS3yvMhDoWjU0ybJr4i7xP0Hd1-pYluxS4A
Content-Type: application/json

{
    "title": "second post",
    "content": "second post content lorem ipsum dolor sit amet"
}

###

POST http://localhost:3001/blogs/new
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InJlbmF0YWRhbmluc2t5QHRlc3QuY29tIiwidXNlcklkIjoiNjA3YTAxMTUwODdhNmI2MWY4ZDYxYjdiIiwiaWF0IjoxNjE4NjA4NDE4LCJleHAiOjE2MTg2MTIwMTh9.EEhiDTmPb71tVyBAGJmCptaTq6hUMiGspz3lAP0K0rI
Content-Type: application/json

{
    "title": "second post from Renata",
    "content": "sRenata renata renata"
}


###

GET http://localhost:3001/blogs
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im11a2VzaGt1cHBhQHRlc3QuY29tIiwidXNlcklkIjoiNjA3YTA3NWQwNmU0NDA2MzBjNTE2MWRmIiwiaWF0IjoxNjE4NjEwMDI1LCJleHAiOjE2MTg2MTM2MjV9.u8G0VFZuItSnMqYLj9_05bEikWPzrom75Da5BSWAfyA

###
POST http://localhost:3001/blogs/new 
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im11a2VzaGt1cHBhQHRlc3QuY29tIiwidXNlcklkIjoiNjA3YTA3NWQwNmU0NDA2MzBjNTE2MWRmIiwiaWF0IjoxNjE4NjEwMDI1LCJleHAiOjE2MTg2MTM2MjV9.u8G0VFZuItSnMqYLj9_05bEikWPzrom75Da5BSWAfyA
Content-Type: application/json

{
    "title": "MUKESH post 3",
    "content": "bullshit scammer content 3"
}