POST http://localhost:3001/users/register
Content-Type: application/json

{
    "name": "test",
    "surname": "test",
    "email": "3testtest@test.com",
    "password": "testpass",
    "nickname": "2testtest"
}

###

POST http://localhost:3001/users/login 
Content-Type: application/json

{
    "email": "mukeshkuppa@test.com",
    "password": "mukeshkuppa"
}

###

POST http://localhost:3001/blogs/new
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAdGVzdC5wbCIsInVzZXJJZCI6IjYwN2JmMGJiNDBkNTgwNjIwMDQ5ZmM1MCIsImlhdCI6MTYxODc1MjczMCwiZXhwIjoxNjE4NzU2MzMwfQ.KyAdAeZAxur6RsGN6WBgoeV95HBC-hpwDE88ZJIzsbE
Content-Type: application/json

{
    "title": "renatka",
    "content": "I can see this!"
}

###

POST http://localhost:3001/comments/getNumber
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImphbmVTQGhvdG1haWwucnUiLCJ1c2VySWQiOiI2MDkzZjE1MzJmYTI5MDNjOTQwZjc5MmQiLCJpYXQiOjE2MjAzMzY1NDQsImV4cCI6MTYyMDM0MDE0NH0.GPaZCzR_pBpR_sLcOgXVdPv0npUruiTgwhJ6BfISdVA
Content-Type: application/json

{
    "blogId": "6093f1b82fa2903c940f792e",
}

