export const ADD_FRIEND = 'ADD_FRIEND';
export const CLEAR_FULLFRIENDS = 'CLEAR_FULLFRIENDS';
export const CHECK_STORE = 'CHECK_STORE';
export const REMOVE_NOTIF_FRIENDREQ = 'REMOVE_NOTIF_FRIENDREQ';

